# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fxgvcv
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: sarc
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sarc

custom:
  wsgi:
    app: src.app.app

provider:
  name: aws
  role: arn:aws:iam::023177117893:role/LabRole
  runtime: python3.11
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID_1}
    subnetIds:
      - ${env:SUBNET_ID_1}
      - ${env:SUBNET_ID_2}

package:
  exclude:
    - tests/**
    - '**/__pycache__/**'
    - node_modules/**
    - instance/**
    - terraform/**

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements