name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ env.DB_USERNAME }}
      DB_PASSWORD: ${{ env.DB_PASSWORD }}
      DB_NAME: ${{ env.DB_NAME }}
      AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: ${{ env.AWS_ROLE_ARN }}
      SECURITY_GROUP_ID_1: ${{ env.SECURITY_GROUP_ID_1 }}
      SUBNET_ID_1: ${{ env.SUBNET_ID_1 }}
      SUBNET_ID_2: ${{ env.SUBNET_ID_2 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var="db_username=$DB_USERNAME" \
            -var="db_password=$DB_PASSWORD" \
            -var="db_name=$DB_NAME"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Serverless
        run: npm install -g serverless

      - name: Serverless Deploy
        run: serverless deploy